### ISSUE TITLE
Curve swap pools are hardcoded

### ISSUE THREAD

**Issue by mattiaslightstone** [rahul-kothari/hack-money-ape#10]
Curve swap pool addresses are used to determine the price of curve lp tokens.

At the moment the mapping between the curve lp token (ERC20) address and the swap pool address are inputed manually.

Curve has a deployed addresses contract where this information could be fetched from.

Note: Some curve pools have contracts that function as both the erc20 token, and the swap contract (e.g. alusd, mim3crv ...)

**Comment by rahul-kothari** [comment]
Can we close this now?

**Comment by mattiaslightstone** [comment]
Handled by PR #11
